ParamSummaryLength: 150 # This is what is used for generating summary. Do not use 'summaryLength'.

hb:
  back_to_top:
    icon_name: arrow-up-circle
  blog:
    #giscus:
    #  category: Giscus
    #  category_id: DIC_kwDOKakTSM4CZxf_
    #  languages_mapping.ko: ko
    #  repo: TetraTheta/TetraLogComment
    #  repo_id: R_kgDOKakTSA
    home:
      featured_posts: 3 # the number of the featured posts.
    paginate: 12
    post_read_more: false
    related_posts:
      list_style: slide
    sidebar:
      position: end
      posts:
        recent_posts: 10
      sticky: false
      taxonomies:
        authors:
          disable: true
        separate: true
    terms:
      paginate: 12
  color: dark
  docs:
    meta:
      authors: false
  footer:
    # see https://hbstack.dev/en/docs/modules/socials/.
    socials:
      _color: true # when false, remove the color of social icons.
      github: TetraTheta
      rss: true
  full_width: false
  header:
    brand: TetraLog Game Story # the brand name, leave it empty to use site's title.
    logo_bg: "#00000000" # logo background color, used by logo with transparent background.
    # see https://hbstack.dev/en/docs/modules/socials/.
    socials:
      github: TetraTheta
      rss: true
  heading_sign:
    symbol: "Â¶"
  pagination:
    siblings: 3
  progress_bar:
    height: 4px
  tables:
    align: middle
  terms:
    paginate: 12
    profile: false

hugopress:
  modules:
    hb-custom:
      hooks:
        hb-blog-post-meta:
          cacheable: false
        head-end:
          cacheable: true
        body-end:
          cacheable: true

# Default Open Graph / Twitter Cards image
# images:
#   - images/card-twitter.png

mermaid:
  js_url: https://cdn.jsdelivr.net/npm/mermaid@latest/dist/mermaid.esm.min.mjs

# see https://hugomods.com/en/docs/search/#site-parameters
search:
  case_sensitive: false
  expand_results_meta: true
  ignore_location: true
  index_content: true
  min_match_char_length: 2
  stall_threshold: 900
  threshold: 0.0

seo:
  favicons:
    icon: images/logo.png
